#cloud-config

package_update: true
packages:
  - zsh
  - unzip

groups:
  - docker
users:
  - name: workspace-user
    groups: sudo, docker
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash

runcmd:
  - chown -R workspace-user:workspace-user /home/workspace-user
  - chsh -s /bin/zsh workspace-user
